### ISSUE TITLE
ex:nil - returns the next value available instead of NULL or EMPTY

### ISSUE THREAD

**Issue by blesjil** [maddingo/sojo#10]
For Parameters with ex:nil value is replace with the next available key value.

XmlRpcContentHandler.java		
else if (lvCurrentStackObj instanceof Map) {
				Map<Object, Object> lvMap = (Map<Object, Object>) lvCurrentStackObj;
				lvMap.put(pvName, pvValue);
				if ("key".equals(pvName)) {
					for (Map.Entry<?, Object> lvEntry : lvMap.entrySet()) {
						if (lvEntry.getValue() == null) {
							lvEntry.setValue(pvValue); ---> this replaces the null value to the next available value.
						}
					}
				}
				lvMap.remove("key");

**Comment by maddingo** [comment]
This issue is now fixed.
